[[at_spi2_core]]
arch = "aarch64"
git-tree-sha1 = "a4f07a8dc09b6caadc3f7309f5718914b1806a81"
libc = "glibc"
os = "linux"

    [[at_spi2_core.download]]
    sha256 = "90e48db24468521b4066a2419faef9dfa5a59e6f3f21f2a4f23da1eab5261df9"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_core_jll.jl/releases/download/at_spi2_core-v2.58.2+0/at_spi2_core.v2.58.2.aarch64-linux-gnu.tar.gz"
[[at_spi2_core]]
arch = "aarch64"
git-tree-sha1 = "dd729e3dda1e3b8ef466040d7d00ff01c39a3c28"
libc = "musl"
os = "linux"

    [[at_spi2_core.download]]
    sha256 = "1d25c115834f35fd14d357b5de98679fc47d19cbe8ab0c938e8e6ac434f1d4d7"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_core_jll.jl/releases/download/at_spi2_core-v2.58.2+0/at_spi2_core.v2.58.2.aarch64-linux-musl.tar.gz"
[[at_spi2_core]]
arch = "aarch64"
git-tree-sha1 = "d128ed2434522d21162bd020ebf6a524d2e2c294"
os = "freebsd"

    [[at_spi2_core.download]]
    sha256 = "d50420fd7cb0b8f6a4f0ebb7f91960bfc792c58454796f08c154ca5c56d41c4a"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_core_jll.jl/releases/download/at_spi2_core-v2.58.2+0/at_spi2_core.v2.58.2.aarch64-unknown-freebsd.tar.gz"
[[at_spi2_core]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "074b5e63259d2a70dcc83bb894dbfcbb00a65a2c"
libc = "glibc"
os = "linux"

    [[at_spi2_core.download]]
    sha256 = "e0b3b2c2a5621aa03ba4cc98d9fe789c93160db13b790854614884f224124478"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_core_jll.jl/releases/download/at_spi2_core-v2.58.2+0/at_spi2_core.v2.58.2.armv6l-linux-gnueabihf.tar.gz"
[[at_spi2_core]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "669179c481ad8ed4e26ad31bd39db4c8b568b9c4"
libc = "musl"
os = "linux"

    [[at_spi2_core.download]]
    sha256 = "1651157388271d214c3c2f4b6491c28ccdf0ce1987bc514a78aa342307d91229"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_core_jll.jl/releases/download/at_spi2_core-v2.58.2+0/at_spi2_core.v2.58.2.armv6l-linux-musleabihf.tar.gz"
[[at_spi2_core]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "79b0ae366d64d0962ae7b593826b1c827490266e"
libc = "glibc"
os = "linux"

    [[at_spi2_core.download]]
    sha256 = "39b9cd9dec155e00f5b9894c7c05584e3cf2e623d6397a739e8828287fe789dd"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_core_jll.jl/releases/download/at_spi2_core-v2.58.2+0/at_spi2_core.v2.58.2.armv7l-linux-gnueabihf.tar.gz"
[[at_spi2_core]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fed6e4616551d5236ae776f8f2d0902d78a95e13"
libc = "musl"
os = "linux"

    [[at_spi2_core.download]]
    sha256 = "a9259ab553e50ff486d5b7c6c955f6169ace94c410ce1047e9678d464ac4f716"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_core_jll.jl/releases/download/at_spi2_core-v2.58.2+0/at_spi2_core.v2.58.2.armv7l-linux-musleabihf.tar.gz"
[[at_spi2_core]]
arch = "i686"
git-tree-sha1 = "6523b6542de62e2c0c26fddeed7029eb7cec1c60"
libc = "glibc"
os = "linux"

    [[at_spi2_core.download]]
    sha256 = "a4252ee7f16dd5999360556d039afced58d7785587bc074a5b19c529daad1318"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_core_jll.jl/releases/download/at_spi2_core-v2.58.2+0/at_spi2_core.v2.58.2.i686-linux-gnu.tar.gz"
[[at_spi2_core]]
arch = "i686"
git-tree-sha1 = "1dee66f8e7d6fe3004e30911b1ad9b0c74129353"
libc = "musl"
os = "linux"

    [[at_spi2_core.download]]
    sha256 = "c4a562c099e158f31eab6d493650618266de6027f6d2a0da61c6d8d4923ab06b"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_core_jll.jl/releases/download/at_spi2_core-v2.58.2+0/at_spi2_core.v2.58.2.i686-linux-musl.tar.gz"
[[at_spi2_core]]
arch = "powerpc64le"
git-tree-sha1 = "2c7bb4f253a33af7163aadb17b3cf274ff9ef52d"
libc = "glibc"
os = "linux"

    [[at_spi2_core.download]]
    sha256 = "246d7c1d4147d29d5dbe9f418d1eb33ee055f79d2ac7fa1e942aaf5696ebe553"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_core_jll.jl/releases/download/at_spi2_core-v2.58.2+0/at_spi2_core.v2.58.2.powerpc64le-linux-gnu.tar.gz"
[[at_spi2_core]]
arch = "riscv64"
git-tree-sha1 = "003676bfe9d8ad0ec18791616fb443c87cd11d32"
libc = "glibc"
os = "linux"

    [[at_spi2_core.download]]
    sha256 = "341f0243f51c52fd870920b287ccf52bcce0a9fafd402388358ec20eae640f23"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_core_jll.jl/releases/download/at_spi2_core-v2.58.2+0/at_spi2_core.v2.58.2.riscv64-linux-gnu.tar.gz"
[[at_spi2_core]]
arch = "x86_64"
git-tree-sha1 = "bdde8f30c6bdff912ff81edce39775b7c35df4a5"
libc = "glibc"
os = "linux"

    [[at_spi2_core.download]]
    sha256 = "e57b9063f2624ebc6936b188ae34ba69f6537bd50ed71c769d9d2ac25ccd70cf"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_core_jll.jl/releases/download/at_spi2_core-v2.58.2+0/at_spi2_core.v2.58.2.x86_64-linux-gnu.tar.gz"
[[at_spi2_core]]
arch = "x86_64"
git-tree-sha1 = "36da5a6c06cf0a320ee4f47fbcf408f5f51f041d"
libc = "musl"
os = "linux"

    [[at_spi2_core.download]]
    sha256 = "ee639bb4ae5d9be571718f696f718f6a8f2de9a9b875b16ef5c93b60176c1f9a"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_core_jll.jl/releases/download/at_spi2_core-v2.58.2+0/at_spi2_core.v2.58.2.x86_64-linux-musl.tar.gz"
[[at_spi2_core]]
arch = "x86_64"
git-tree-sha1 = "b3dee189598ab07e861178abcfde2c5990976f86"
os = "freebsd"

    [[at_spi2_core.download]]
    sha256 = "e8ec140b3b177986f113e1673657fb15e3c4c0d2ecd4b920656de1e487dc5710"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_core_jll.jl/releases/download/at_spi2_core-v2.58.2+0/at_spi2_core.v2.58.2.x86_64-unknown-freebsd.tar.gz"
